apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_API_BASE: ""
  API_PROXY_TARGET: "http://backend.fresher-connect.svc.cluster.local:5000"
