from __future__ import annotations


def build_company_document(
    *,
    company_id,
    name,
    email,
    password_hash,
    company_name,
    company_logo,
    company_website,
    industry_type,
    company_size,
    company_description,
    location,
    created_at,
):
    return {
        "company_id": company_id,
        "role": "company",
        "contact_name": name,
        "name": name,
        "email": email,
        "password_hash": password_hash,
        "company_name": company_name,
        "company_logo": company_logo,
        "company_website": company_website,
        "industry_type": industry_type,
        "company_size": company_size,
        "company_description": company_description,
        "location": location,
        "created_at": created_at,
        "updated_at": created_at,
    }


def build_user_document(
    *,
    user_id,
    name,
    email,
    password_hash,
    phone,
    location,
    education,
    grad_year,
    skills,
    summary,
    resume_path,
    created_at,
):
    return {
        "user_id": user_id,
        "role": "fresher",
        "name": name,
        "email": email,
        "password_hash": password_hash,
        "phone": phone,
        "location": location,
        "education": education,
        "grad_year": grad_year,
        "skills": skills,
        "summary": summary,
        "resume_path": resume_path,
        "is_premium": False,
        "created_at": created_at,
        "updated_at": created_at,
    }


def merge_company_profile(company, payload, updated_at):
    updated = dict(company)
    updated.update(
        {
            "company_name": str(payload.get("company_name") or company.get("company_name") or "").strip(),
            "company_logo": str(payload.get("company_logo") or company.get("company_logo") or "").strip(),
            "company_website": str(payload.get("company_website") or company.get("company_website") or "").strip(),
            "industry_type": str(payload.get("industry_type") or company.get("industry_type") or "").strip(),
            "company_size": str(payload.get("company_size") or company.get("company_size") or "").strip(),
            "company_description": str(payload.get("company_description") or company.get("company_description") or "").strip(),
            "location": str(payload.get("location") or company.get("location") or "").strip(),
            "updated_at": updated_at,
        }
    )
    return updated


def build_job_document(
    *,
    job_id,
    company_doc,
    title,
    description,
    experience_required,
    education_required,
    salary_min,
    salary_max,
    location,
    employment_type,
    required_skills,
    posted_date,
    expiry_date,
    department,
    work_mode,
    country,
    state,
    city,
    remote_option,
    role_overview,
    responsibilities,
    required_qualifications,
    preferred_qualifications,
    salary_range,
    internship_stipend,
    benefits,
    application_method,
    application_url,
    application_email,
    resume_required,
    portfolio_required,
    cover_letter_required,
    hiring_stages,
    categories,
    created_at,
):
    return {
        "job_id": job_id,
        "company_id": company_doc["company_id"],
        "job_title": title,
        "job_description": description,
        "experience_required": experience_required,
        "education_required": education_required,
        "salary_min": salary_min,
        "salary_max": salary_max,
        "location": location,
        "employment_type": employment_type,
        "skills": required_skills,
        "posted_date": posted_date,
        "expiry_date": expiry_date,
        "company_name": company_doc["company_name"],
        "company_logo": company_doc.get("company_logo"),
        "company_website": company_doc.get("company_website"),
        "industry_type": company_doc.get("industry_type"),
        "company_size": company_doc.get("company_size"),
        "company_description": company_doc.get("company_description"),
        "department": department,
        "experience_level": experience_required,
        "job_type": employment_type,
        "work_mode": work_mode,
        "country": country,
        "state": state,
        "city": city,
        "remote_option": remote_option,
        "degree_required": education_required,
        "required_skills": required_skills,
        "description": description,
        "role_overview": role_overview,
        "responsibilities": responsibilities,
        "required_qualifications": required_qualifications,
        "preferred_qualifications": preferred_qualifications,
        "requirements": required_qualifications,
        "salary_range": salary_range,
        "internship_stipend": internship_stipend,
        "benefits": benefits,
        "application_method": application_method,
        "application_url": application_url,
        "application_email": application_email,
        "resume_required": resume_required,
        "portfolio_required": portfolio_required,
        "cover_letter_required": cover_letter_required,
        "hiring_stages": hiring_stages,
        "categories": categories,
        "is_active": True,
        "created_at": created_at,
        "updated_at": created_at,
    }
